export type SupportedLocale = 'ko' | 'en' | 'ja' | 'zh'

function normalizeLocale(locale: string): SupportedLocale {
  if (locale === 'en' || locale === 'ja' || locale === 'zh') {
    return locale
  }

  return 'ko'
}

const copy = {
  ko: {
    language: {
      changeTitle: '언어 변경',
    },
    register: {
      strengthLabels: ['매우 약함', '약함', '보통', '강함', '매우 강함'],
      passwordTyping: '입력 중',
      passwordMismatch: '비밀번호가 일치하지 않습니다.',
      passwordMin: '비밀번호는 최소 8자 이상이어야 합니다.',
      registerSuccess: '회원가입이 완료되었습니다! 이메일을 확인해 주세요.',
      createAccount: '계정 생성',
      passwordStrength: '비밀번호 강도',
      passwordGuide: '최소 8자, 대문자, 숫자, 특수문자 포함 권장',
      passwordMatch: '비밀번호가 일치합니다',
      passwordMismatchInline: '비밀번호가 일치하지 않습니다',
      registerFailTitle: '회원가입 실패',
      successTitle: '성공!',
      signingUp: '가입 중...',
      signUp: '회원가입',
      or: '또는',
      alreadyHaveAccount: '이미 계정이 있으신가요?',
      login: '로그인',
      footer: '개인 자산 관리',
      emailLabel: '이메일',
      emailPlaceholder: 'name@example.com',
      passwordLabel: '비밀번호',
      passwordPlaceholder: '비밀번호 입력',
      confirmPasswordLabel: '비밀번호 확인',
      confirmPasswordPlaceholder: '비밀번호를 다시 입력',
    },
    login: {
      liveWorkspace: 'Live workspace',
      screenTitle: '오늘의 금융 화면',
      netWorth: '순자산',
      weekGain: '이번 주 +2.4%',
      recentExpense: '최근 지출',
      goalProgress: '목표 진행',
      recentTransactions: '최근 거래',
      today: 'Today',
      food: '식비',
      salary: '급여',
      investment: '투자',
      or: '또는',
      sampleLunch: '점심',
      sampleSalary: '월급',
      sampleEtf: 'ETF 매수',
      emailPlaceholder: 'name@example.com',
      passwordPlaceholder: '비밀번호 입력',
    },
    authRecovery: {
      forgotTitle: '비밀번호 재설정',
      forgotDesc: '가입한 이메일 주소를 입력하면 비밀번호 재설정 링크를 보내드립니다.',
      emailLabel: '이메일 주소',
      emailPlaceholder: 'name@example.com',
      sendReset: '재설정 링크 보내기',
      genericError: '오류가 발생했습니다.',
      unexpectedError: '예상치 못한 오류가 발생했습니다. 다시 시도해 주세요.',
      resetTitle: '새 비밀번호 설정',
      resetDesc: '로그인된 상태입니다. 아래에서 새 비밀번호를 입력해 주세요.',
      authError: '인증 정보를 확인할 수 없습니다. 새 비밀번호 재설정 링크로 다시 시도해 주세요.',
      passwordMismatch: '비밀번호가 일치하지 않습니다.',
      passwordMin: '비밀번호는 최소 6자 이상이어야 합니다.',
      passwordUpdated: '비밀번호가 변경되었습니다. 로그아웃 후 로그인 화면으로 이동합니다.',
      newPasswordLabel: '새 비밀번호',
      newPasswordPlaceholder: '새 비밀번호 입력 (최소 6자)',
      confirmPasswordLabel: '새 비밀번호 확인',
      confirmPasswordPlaceholder: '새 비밀번호를 다시 입력',
      submitReset: '비밀번호 변경',
    },
    analysis: {
      label: '분석',
      error: '분석 데이터를 불러오지 못했습니다.',
      emptyTitle: '현재 데이터가 존재하지 않습니다.',
      emptyDesc: '거래 내역이나 예산을 입력하면 월별 분석과 카테고리 분석이 여기에 표시됩니다.',
      thisMonth: '이번 달',
      netSavings: '순저축',
      monthOverMonth: '전월 대비',
      expenseChange: '지출 변화',
      exchangeFlow: '환전 흐름',
      exchangeFlowDesc: '월별 환전 건수와 환전 규모를 따로 확인합니다.',
      exchangeCount: (count: number) => `환전 ${count}건`,
      openSettings: '설정 열기',
      budgetSetup: '예산 설정',
      recurringSetup: '반복거래 설정',
      overBudgetCount: (count: number) => `초과 예산 ${count}개`,
      budgetHint: '월별 예산을 등록하고 초과 여부를 확인하세요',
      recurringHintActive: '월세, 구독료, 급여처럼 반복되는 거래 관리',
      recurringHintEmpty: '반복 거래를 등록해 입력 부담을 줄이세요',
      monthlyCashflow: '월별 현금흐름',
      monthlyCashflowDesc: '최근 12개월 기준 수입, 지출, 순저축 추이입니다.',
      monthlyCategory: '월별 카테고리 분석',
      monthlyCategoryDesc: '이번 달을 기본으로, 원하는 달의 지출 카테고리를 확인할 수 있습니다.',
      noMonthlyCategory: '선택한 달의 카테고리 지출이 아직 없습니다.',
      viewAllCategories: '전체 카테고리 보기',
      yearlyTrend: '연도별 추이',
      yearlyTrendDesc: '연도 단위로 수입과 지출 흐름을 비교합니다.',
      budgetStatus: '예산 상태',
      budgetStatusDesc: '현재 월 예산과 실제 지출을 비교합니다.',
      budgetEmpty: '등록된 월 예산이 아직 없습니다. 예산을 추가하면 초과 여부와 사용률을 여기서 바로 확인할 수 있습니다.',
      daysRemaining: (days: number) => `${days}일 남음`,
      categoryPageLabel: '카테고리 분석',
      categoryPageError: '카테고리 분석 데이터를 불러오지 못했습니다.',
      categoryPageTitle: '전체 카테고리 지출',
      categoryPageDesc: (month: string) => `${month} 기준 모든 지출 카테고리를 확인할 수 있습니다.`,
      backToAnalysis: '분석으로 돌아가기',
      categoryAmount: '카테고리별 금액',
      totalExpense: (amount: string, currency: string) => `총 지출 ${amount} ${currency}`,
      noCategoryExpense: '선택한 달의 지출 카테고리가 아직 없습니다.',
    },
    overview: {
      expenseUp: '지출이 늘고 있어요',
      expenseStable: '지출이 안정적이에요',
      quickAdd: '빠른 추가',
      addTransaction: '거래내역 추가',
      addTransactionDesc: '지출, 수입, 이체를 바로 기록',
      assetSetup: '자산 설정',
      addAccount: '계좌 추가',
      addAccountDesc: '새 계좌나 카드 연결',
      portfolio: '포트폴리오',
      addInvestment: '투자 추가',
      addInvestmentDesc: '보유 종목을 빠르게 등록',
      assetOverview: '자산 요약',
      recent30Days: '최근 30일 기준',
      estimatedBeforeRates: '환율 동기화 전 추정값',
      heroDesc: '오늘 자산 상태와 최근 소비 흐름을 한 번에 보고, 어디를 먼저 손봐야 하는지 빠르게 판단할 수 있게 정리했습니다.',
      recent30DayExpense: '최근 30일 지출',
      investment: '투자',
      averageGoalProgress: '목표 평균 진행률',
      jumpNow: '바로 이동',
      focusPoint: '지금 보면 좋은 포인트',
      focusDescUp: '최근 지출이 직전 흐름보다 커졌습니다. 소비가 늘어난 카테고리를 먼저 확인해보는 게 좋습니다.',
      focusDescStable: '지출 흐름이 비교적 안정적입니다. 남는 현금을 목표나 투자 쪽으로 옮길 여지가 있습니다.',
      basedOnNetWorth: '순자산 기준',
      linkedAccounts: '연결된 계좌 수',
      investmentAssets: '투자 자산 합계',
      expenseChange: '최근 지출 변화',
      dayOverDayExpense: '전일 대비',
      plannedExpenses: '지출 예정',
      plannedExpensesMeta: (recurringCount: number, cardCount: number) => `반복거래 ${recurringCount}건 · 카드 상환 ${cardCount}건`,
      analysisGraphMode: '그래프 보기',
      analysisGraphBar: '막대',
      analysisGraphDot: '점선',
      amountLabel: '금액',
      amountHint: '한 달 기준으로 관리할 예산 금액입니다.',
      currencyLabel: '통화',
      yearLabel: '연도',
      monthLabel: '월',
      krwMirror: '원화 기준 참고 자산',
      activeGoals: '활성 목표 수',
      cashBalance: '현금 잔고',
      cashByCurrency: '통화별 현금 잔고',
      aiShortcutLabel: 'Beta shortcut',
      aiShortcutTitle: 'AI로 등록하기',
      aiShortcutDesc: '여러 건의 거래를 붙여넣고 카테고리까지 한 번에 초안으로 정리할 수 있습니다.',
      openBeta: 'Beta 열기',
      focusNow: '지금 집중할 곳',
      currentGoalLabel: '현재 목표',
      primaryGoalTitle: '최우선 목표',
      currencyBucket: '통화별 구간',
      otherExpenseCategory: '기타',
      expenseSplit: '지출 흐름',
      currencyBalances: '통화별 자산',
      currencyBalancesDesc: '계좌와 투자 자산을 통화 기준으로 함께 확인합니다.',
      baseCurrencyLabel: '기준 통화',
      mirrorCurrencyLabel: '참고 통화',
      mirrorCardLabel: (currency: string) => `${currency} 미러`,
      totalAssetsInCurrency: (currency: string) => `총자산 (${currency})`,
      recentExpenseInCurrency: (currency: string) => `최근 30일 지출 (${currency})`,
      investmentInCurrency: (currency: string) => `투자 (${currency})`,
      expenseChangeInCurrency: (currency: string) => `지출 변화 (${currency})`,
    },
    holdingsForm: {
      genericError: '오류가 발생했습니다.',
      fillRequired: '필수 항목을 모두 입력해 주세요.',
      pickHoldingAction: '추가 매수 또는 매도할 투자 종목을 선택해 주세요.',
      pickSuggestion: '검색 결과에서 종목을 선택해 주세요.',
      numberOnly: '수량과 단가는 숫자로 입력해 주세요.',
      positiveOnly: '수량과 단가는 0보다 커야 합니다.',
      buyTitle: '추가 매수',
      sellTitle: '매도',
      buyDesc: '기존 투자 종목에 수량을 추가하고 평단을 자동으로 계산합니다.',
      sellDesc: '보유한 투자 종목의 수량을 줄이거나 전량 매도합니다.',
      createDesc: '포트폴리오에 주식이나 투자 상품을 추가합니다.',
      actionLabel: '투자 작업',
      createOption: '새 투자 추가',
      buyOption: '추가 매수',
      sellOption: '매도',
      targetHolding: '대상 투자',
      selectHolding: '투자 종목 선택',
      unnamed: '이름 없음',
      currentHolding: (shares: string, cost: string, currency: string) => `현재 보유: ${shares}주 / 평단 ${cost} ${currency}`,
      symbolPlaceholder: '종목명 또는 심볼로 검색',
      searchingSymbol: '종목을 찾는 중...',
      noSymbolResults: '일치하는 종목을 찾지 못했습니다.',
      searchHint: '종목명으로 검색 후 목록에서 선택하면 심볼 미스매치를 줄일 수 있습니다.',
      existingHoldingHint: '추가 매수와 매도는 기존 투자 종목을 기준으로 처리됩니다.',
      sellPrice: '매도가',
      buyPrice: '매수가',
      estimatedSellAmount: '예상 매도 금액',
      estimatedBuyAmount: '추가 매수 금액',
      totalCost: '총 매수 금액',
      symbolLinkWarning: '검색 결과에서 종목을 선택해야 정확한 심볼과 주가 갱신이 연결됩니다.',
      account: '계좌',
      selectAccount: '계좌 선택',
    },
    setup: {
      defaultBudgetName: '식비 예산',
      step1: '계좌',
      step2: '예산',
      step3: '반복거래',
      title: '온보딩 설정',
      desc: '수동 입력 중심 가계부에 맞춰 계좌, 예산, 반복거래를 한 번에 준비합니다.',
      descSub: '지금 다 입력하지 않아도 됩니다. 필요한 것만 적고 나머지는 나중에 추가해도 돼요.',
      languageTitle: '언어 설정',
      languageDesc: '먼저 언어를 정하면 기본 카테고리와 초기 예시도 그 언어 기준으로 맞춰집니다.',
      currencyTitle: '주 사용 통화',
      currencyDesc: '자주 쓰는 통화를 먼저 골라두면 대시보드와 환율 목록이 더 자연스럽게 시작됩니다.',
      baseCurrencyLabel: '기준 통화',
      mirrorCurrencyLabel: '참고 통화',
      trackedCurrenciesLabel: '추적 통화',
      trackedCurrenciesDesc: '최소 두 개를 골라 실제로 보는 환율만 간결하게 유지하세요.',
      securityTitle: '보안 우선 설정',
      securityDesc: '모든 데이터는 로그인된 사용자 소유로만 저장되고, 온보딩 완료 전에는 메인 화면으로 진입하지 않도록 구성했습니다.',
      skip: '지금은 건너뛰기',
      onboardingFailed: '초기 설정에 실패했습니다.',
      skipFailed: '온보딩 건너뛰기에 실패했습니다.',
      accountTitle: '계좌 등록',
      accountDesc: '자주 사용하는 계좌와 초기 잔액을 먼저 세팅해 주세요.',
      accountDescSub: '예시: 생활비 통장, 비상금 통장, 카드 결제 계좌. 비워두면 저장하지 않고 넘어갑니다.',
      addAccount: '계좌 추가',
      accountPlaceholder: '예: 메인 통장',
      delete: '삭제',
      budgetTitle: '월별 예산',
      budgetDesc: '카테고리별 예산을 잡아두면 분석 탭에서 바로 초과 여부를 볼 수 있습니다.',
      budgetDescSub: '예시: 식비 40,000엔, 교통비 12,000엔. 아직 계획이 없다면 비워둬도 됩니다.',
      addBudget: '예산 추가',
      budgetPlaceholder: '예: 식비 예산',
      recurringTitle: '반복거래',
      recurringDesc: '월세, 급여, 구독료처럼 반복되는 거래를 미리 등록해 두세요.',
      recurringDescSub: '예시: 매월 25일 월세, 매월 10일 구독료. 나중에 따로 추가해도 됩니다.',
      addRecurring: '반복거래 추가',
      recurringNamePlaceholder: '예: 월세',
      recurringDescriptionPlaceholder: '설명',
      withdrawalAccount: '출금 계좌',
      depositAccount: '입금 계좌',
      accountSelect: '계좌 선택',
      monthly: '매월',
      weekly: '매주',
      yearly: '매년',
      executionDay: '실행 일자',
      previous: '이전',
      next: '다음',
      saving: '저장 중...',
      complete: '온보딩 완료',
    },
    managers: {
      budgetTitle: '예산 관리',
      budgetDesc: '월별 카테고리 예산을 등록하면 분석 탭에서 초과 여부를 바로 확인할 수 있습니다.',
      budgetPlaceholder: '예: 식비 예산',
      saveBudget: '예산 저장',
      currentBudgets: '현재 예산',
      noBudgets: '등록된 예산이 없습니다.',
      recurringTitle: '반복거래 관리',
      recurringDesc: '월세, 구독료, 급여처럼 반복되는 거래를 미리 등록해 두면 관리가 훨씬 쉬워집니다.',
      recurringNamePlaceholder: '예: 월세',
      recurringDescPlaceholder: '예: 매월 집세',
      selectAccount: '계좌 선택',
      saveRecurring: '반복거래 저장',
      recurringMigrationHint: '현재는 일반 거래 등록으로 계속 사용할 수 있고, 반복거래 테이블이 운영 DB에 적용되면 같은 화면에서 바로 등록할 수 있습니다.',
      currentRecurring: '현재 반복거래',
      noRecurring: '등록된 반복거래가 없습니다.',
      periodMonthLabel: (year: number, month: number) => `${year}.${String(month).padStart(2, '0')}`,
      dayOfMonthLabel: '매월 실행일',
      dayOfMonthHint: '매월 몇 일에 자동으로 등록할지 정합니다.',
      alertThresholdLabel: '알림 기준(%)',
      alertThresholdHint: '예산의 몇 퍼센트부터 경고할지 설정합니다.',
      activeLabel: '활성',
      inactiveLabel: '비활성',
      deleteBudgetConfirm: '정말 이 예산을 삭제하시겠습니까?',
      deleteRecurringConfirm: '정말 이 반복거래를 삭제하시겠습니까?',
      saveChanges: '변경사항 저장',
      categoryTitle: '카테고리 관리',
      categoryDesc: '거래 입력에서 사용할 수입/지출 카테고리를 직접 추가할 수 있습니다.',
      categoryPlaceholder: '예: 반려동물, 경조사',
      addCategory: '카테고리 추가',
      currentCategories: '현재 카테고리',
      defaultTag: '기본',
      customTag: '사용자',
      createCategoryFailed: '카테고리를 추가하지 못했습니다.',
      deleteCategoryFailed: '카테고리를 삭제하지 못했습니다.',
      updateCategoryFailed: '카테고리를 수정하지 못했습니다.',
    },
    investmentPortfolio: {
      loadError: '투자 정보를 불러오는 중 오류가 발생했습니다.',
      empty: '등록된 투자가 없습니다.',
      deleteAction: '삭제',
      deleteConfirm: '정말 이 투자를 삭제하시겠습니까? 계좌 잔액에는 영향을 주지 않고 투자 기록만 제거됩니다.',
      deleteFailed: '투자를 삭제하지 못했습니다.',
      totalCount: (count: number) => `총 ${count}개의 투자 종목`,
      portfolioValue: '포트폴리오 가치',
      marketValueHint: '자동 갱신 현재가 기준 평가 금액 (JPY)',
      totalGainLoss: '총 손익',
      cumulativeReturn: '누적 투자 수익',
      nisaLimit: 'NISA 투자 한도 (성장투자전략)',
      annualLimit: '연간 120만엔',
      usedAmount: '사용 금액',
      remainingLimit: '잔여 한도',
      byType: '투자 유형별',
      regular: '일반',
      itemCount: (count: number) => `${count}개 종목`,
      byMarket: '시장별 분포',
      jpMarket: '일본 시장',
      usMarket: '미국 시장',
      diversification: '투자 비중',
      holdingsCta: '새 투자부터 추가해 포트폴리오를 시작해보세요.',
    },
    bulkImport: {
      failed: '거래 내역 일괄 입력 실패',
      success: '거래 내역이 성공적으로 입력되었습니다!',
      dateRequired: '날짜를 입력해 주세요.',
      descriptionRequired: '설명을 입력해 주세요.',
      amountRequired: '유효한 금액을 입력해 주세요.',
      accountRequired: '계좌를 선택해 주세요.',
      fillAll: '모든 필드를 입력해 주세요.',
      accountNotFound: (name: string) => `계좌를 찾을 수 없습니다: ${name}`,
      csvParseError: (message: string) => `CSV 파일 파싱 오류: ${message}`,
      noTransactions: '입력할 거래 내역이 없습니다.',
      fixErrors: '오류가 있는 거래 내역이 있습니다. 수정해 주세요.',
      title: '거래 내역 일괄 입력',
      subtitle: '여러 거래 내역을 한 번에 입력하세요',
      methodTitle: '입력 방법 선택',
      manual: '수동 입력',
      manualDesc: '한 번에 하나씩 입력',
      csv: 'CSV 업로드',
      csvDesc: '파일에서 일괄 입력',
      addEntryTitle: '거래 내역 추가',
      date: '날짜',
      account: '계좌',
      selectAccount: '계좌 선택',
      description: '설명',
      descriptionPlaceholder: '예: 점심 식사',
      amount: '금액',
      type: '유형',
      addRow: '거래 추가',
      csvUploadTitle: 'CSV 파일 업로드',
      csvDrop: 'CSV 파일을 여기에 드래그하거나 클릭',
      csvFormat: '형식: 날짜, 설명, 유형, 금액, 계좌명, 통화',
      csvExample: 'CSV 형식 예시',
      scheduled: (count: number) => `입력 예정 거래 (${count}개)`,
      dateLabel: (date: string) => `날짜: ${date}`,
      accountLabel: (account: string) => `계좌: ${account}`,
      typeLabel: (type: string) => `유형: ${type}`,
      importing: '입력 중...',
      submit: (count: number) => `거래 내역 입력 (${count}개)`,
      errorTitle: '거래 내역 입력 오류',
    },
    transactionForm: {
      duplicateError: '이미 같은 날짜, 금액, 유형, 내용의 거래가 등록되어 있습니다.',
      applyBalance: '현재 계좌 잔액에 반영',
      applyBalanceDesc: '오늘 거래는 자동으로 잔액에 반영됩니다. 과거 거래는 기본적으로 거래 내역만 기록하고, 필요할 때만 수동으로 반영할 수 있습니다.',
      todayAuto: '오늘 거래라서 잔액이 자동 반영됩니다.',
      pastOptional: '과거 거래입니다. 체크하면 현재 잔액까지 함께 보정합니다.',
      duplicateHint: '중복 가능성이 높은 거래가 이미 있습니다.',
      descriptionPlaceholder: '예: 점심, 월급',
    },
    transactionList: {
      selectAll: (count: number) => `전체 선택 (${count})`,
      notAvailable: '-',
    },
    goals: {
      workspaceLabel: '목표 워크스페이스',
      classicSubtitle: '목표를 설정하고 진행 상황을 한눈에 확인하세요.',
    },
  },
  en: {
    language: { changeTitle: 'Change language' },
    register: {
      strengthLabels: ['Very weak', 'Weak', 'Fair', 'Strong', 'Very strong'],
      passwordTyping: 'Typing',
      passwordMismatch: 'Passwords do not match.',
      passwordMin: 'Password must be at least 8 characters long.',
      registerSuccess: 'Your account has been created. Please check your email.',
      createAccount: 'Create account',
      passwordStrength: 'Password strength',
      passwordGuide: 'Use 8+ characters, ideally with uppercase letters, numbers, and symbols.',
      passwordMatch: 'Passwords match',
      passwordMismatchInline: 'Passwords do not match',
      registerFailTitle: 'Sign-up failed',
      successTitle: 'Success!',
      signingUp: 'Creating account...',
      signUp: 'Sign up',
      or: 'OR',
      alreadyHaveAccount: 'Already have an account?',
      login: 'Log in',
      footer: 'Personal finance workspace',
      emailLabel: 'Email',
      emailPlaceholder: 'name@example.com',
      passwordLabel: 'Password',
      passwordPlaceholder: 'Enter password',
      confirmPasswordLabel: 'Confirm password',
      confirmPasswordPlaceholder: 'Re-enter password',
    },
    login: {
      liveWorkspace: 'Live workspace',
      screenTitle: 'Today’s finance view',
      netWorth: 'Net worth',
      weekGain: '+2.4% this week',
      recentExpense: 'Recent spend',
      goalProgress: 'Goal progress',
      recentTransactions: 'Recent activity',
      today: 'Today',
      food: 'Food',
      salary: 'Salary',
      investment: 'Investment',
      or: 'OR',
      sampleLunch: 'Lunch',
      sampleSalary: 'Salary',
      sampleEtf: 'ETF buy',
      emailPlaceholder: 'name@example.com',
      passwordPlaceholder: 'Enter password',
    },
    authRecovery: {
      forgotTitle: 'Reset your password',
      forgotDesc: 'Enter your email address and we will send you a reset link.',
      emailLabel: 'Email address',
      emailPlaceholder: 'name@example.com',
      sendReset: 'Send reset link',
      genericError: 'An error occurred.',
      unexpectedError: 'An unexpected error occurred. Please try again.',
      resetTitle: 'Set a new password',
      resetDesc: 'You are signed in. Enter your new password below.',
      authError: 'Authentication could not be verified. Please use a new password reset link.',
      passwordMismatch: 'Passwords do not match.',
      passwordMin: 'Password must be at least 6 characters long.',
      passwordUpdated: 'Your password was updated. You will be signed out and redirected to the login page.',
      newPasswordLabel: 'New password',
      newPasswordPlaceholder: 'Enter new password (min. 6 characters)',
      confirmPasswordLabel: 'Confirm new password',
      confirmPasswordPlaceholder: 'Re-enter new password',
      submitReset: 'Update password',
    },
    analysis: {
      label: 'Analysis',
      error: 'Unable to load analysis data.',
      emptyTitle: 'No data is available yet.',
      emptyDesc: 'Add transactions or budgets and your monthly and category insights will appear here.',
      thisMonth: 'This month',
      netSavings: 'Net savings',
      monthOverMonth: 'vs previous month',
      expenseChange: 'Expense change',
      exchangeFlow: 'Exchange flow',
      exchangeFlowDesc: 'Review monthly exchange activity separately from normal spending.',
      exchangeCount: (count: number) => `${count} exchanges`,
      openSettings: 'Open settings',
      budgetSetup: 'Budget setup',
      recurringSetup: 'Recurring setup',
      overBudgetCount: (count: number) => `${count} budgets over limit`,
      budgetHint: 'Create monthly budgets to track overages here.',
      recurringHintActive: 'Manage rent, subscriptions, salary, and other recurring entries.',
      recurringHintEmpty: 'Add recurring entries to reduce manual input.',
      monthlyCashflow: 'Monthly cash flow',
      monthlyCashflowDesc: 'Income, expense, and net savings for the last 12 months.',
      monthlyCategory: 'Monthly category analysis',
      monthlyCategoryDesc: 'Start with the current month and switch to past months whenever you need.',
      noMonthlyCategory: 'No category spend is recorded for the selected month yet.',
      viewAllCategories: 'View all categories',
      yearlyTrend: 'Yearly trend',
      yearlyTrendDesc: 'Compare income and expense movement by year.',
      budgetStatus: 'Budget status',
      budgetStatusDesc: 'Compare current monthly budgets against actual spending.',
      budgetEmpty: 'No monthly budgets have been added yet. Add one to track usage and overages here.',
      daysRemaining: (days: number) => `${days} days left`,
      categoryPageLabel: 'Category analysis',
      categoryPageError: 'Unable to load category analysis data.',
      categoryPageTitle: 'All category spending',
      categoryPageDesc: (month: string) => `See every spending category for ${month}.`,
      backToAnalysis: 'Back to analysis',
      categoryAmount: 'Category amounts',
      totalExpense: (amount: string, currency: string) => `Total spend ${amount} ${currency}`,
      noCategoryExpense: 'No spending categories exist for the selected month yet.',
    },
    overview: {
      expenseUp: 'Spending is rising',
      expenseStable: 'Spending looks stable',
      quickAdd: 'Quick add',
      addTransaction: 'Add transaction',
      addTransactionDesc: 'Record expense, income, or transfer right away',
      assetSetup: 'Assets',
      addAccount: 'Add account',
      addAccountDesc: 'Connect a new account or card',
      portfolio: 'Portfolio',
      addInvestment: 'Add investment',
      addInvestmentDesc: 'Save a holding in a few taps',
      assetOverview: 'Asset overview',
      recent30Days: 'Based on the last 30 days',
      estimatedBeforeRates: 'Estimated before FX sync',
      heroDesc: 'See your asset position and recent spending flow at a glance so you can decide what needs attention first.',
      recent30DayExpense: '30-day spending',
      investment: 'Investments',
      averageGoalProgress: 'Average goal progress',
      jumpNow: 'Open',
      focusPoint: 'Worth checking now',
      focusDescUp: 'Recent spending is higher than the previous stretch. It may help to review the categories that grew.',
      focusDescStable: 'Spending is relatively stable. You may have room to move spare cash toward goals or investing.',
      basedOnNetWorth: 'Based on net worth',
      linkedAccounts: 'Linked accounts',
      investmentAssets: 'Invested assets',
      expenseChange: 'Recent expense change',
      dayOverDayExpense: 'vs prev day',
      plannedExpenses: 'Planned spending',
      plannedExpensesMeta: (recurringCount: number, cardCount: number) => `${recurringCount} recurring · ${cardCount} card payments`,
      analysisGraphMode: 'Chart mode',
      analysisGraphBar: 'Bars',
      analysisGraphDot: 'Dots',
      amountLabel: 'Amount',
      amountHint: 'The budget amount you want to manage for the selected month.',
      currencyLabel: 'Currency',
      yearLabel: 'Year',
      monthLabel: 'Month',
      krwMirror: 'KRW reference view',
      activeGoals: 'Active goals',
      cashBalance: 'Cash balances',
      cashByCurrency: 'Cash by currency',
      aiShortcutLabel: 'Beta shortcut',
      aiShortcutTitle: 'Draft with AI',
      aiShortcutDesc: 'Paste multiple entries and let the app draft categories and structure in one pass.',
      openBeta: 'Open beta',
      focusNow: 'Focus now',
      currentGoalLabel: 'Current goal',
      primaryGoalTitle: 'Top goal',
      currencyBucket: 'Currency bucket',
      otherExpenseCategory: 'Other',
      expenseSplit: 'Expense split',
      currencyBalances: 'Assets by currency',
      currencyBalancesDesc: 'View account balances and investment assets together by currency.',
      baseCurrencyLabel: 'Base currency',
      mirrorCurrencyLabel: 'Reference currency',
      mirrorCardLabel: (currency: string) => `${currency} mirror`,
      totalAssetsInCurrency: (currency: string) => `Total assets (${currency})`,
      recentExpenseInCurrency: (currency: string) => `30-day spending (${currency})`,
      investmentInCurrency: (currency: string) => `Investments (${currency})`,
      expenseChangeInCurrency: (currency: string) => `Expense change (${currency})`,
    },
    holdingsForm: {
      genericError: 'An error occurred.',
      fillRequired: 'Please fill in all required fields.',
      pickHoldingAction: 'Choose the holding you want to buy more of or sell.',
      pickSuggestion: 'Select a symbol from the search results.',
      numberOnly: 'Shares and price must be numbers.',
      positiveOnly: 'Shares and price must be greater than 0.',
      buyTitle: 'Buy more',
      sellTitle: 'Sell',
      buyDesc: 'Add more shares to an existing position and recalculate the average cost automatically.',
      sellDesc: 'Reduce shares from an existing position or sell the full position.',
      createDesc: 'Add a stock or investment product to your portfolio.',
      actionLabel: 'Investment action',
      createOption: 'Add new investment',
      buyOption: 'Buy more',
      sellOption: 'Sell',
      targetHolding: 'Target holding',
      selectHolding: 'Select holding',
      unnamed: 'Unnamed',
      currentHolding: (shares: string, cost: string, currency: string) => `Current: ${shares} shares / avg ${cost} ${currency}`,
      symbolPlaceholder: 'Search by company or symbol',
      searchingSymbol: 'Searching symbols...',
      noSymbolResults: 'No matching symbols found.',
      searchHint: 'Select from search results to avoid symbol mismatch.',
      existingHoldingHint: 'Buy and sell actions use an existing holding as the base.',
      sellPrice: 'Sell price',
      buyPrice: 'Buy price',
      estimatedSellAmount: 'Estimated sell amount',
      estimatedBuyAmount: 'Estimated buy amount',
      totalCost: 'Total cost',
      symbolLinkWarning: 'Choose a search result so price updates stay linked to the correct symbol.',
      account: 'Account',
      selectAccount: 'Select account',
    },
    setup: {
      defaultBudgetName: 'Food budget',
      step1: 'Accounts',
      step2: 'Budgets',
      step3: 'Recurring',
      title: 'Onboarding setup',
      desc: 'Prepare your manual finance workspace with accounts, budgets, and recurring entries in one flow.',
      descSub: 'You do not need to fill everything in now. Add only what you need and come back later.',
      languageTitle: 'Language',
      languageDesc: 'Set your language first so starter categories and examples match it.',
      currencyTitle: 'Primary currencies',
      currencyDesc: 'Pick the currencies you actually use so the dashboard and exchange list start in a cleaner state.',
      baseCurrencyLabel: 'Base currency',
      mirrorCurrencyLabel: 'Reference currency',
      trackedCurrenciesLabel: 'Tracked currencies',
      trackedCurrenciesDesc: 'Choose at least two to keep rates and auto updates focused on what you really use.',
      securityTitle: 'Security first',
      securityDesc: 'Every record is stored only for the signed-in user, and the main app stays locked until onboarding is complete.',
      skip: 'Skip for now',
      onboardingFailed: 'Failed to complete onboarding.',
      skipFailed: 'Failed to skip onboarding.',
      accountTitle: 'Add accounts',
      accountDesc: 'Set up the accounts and starting balances you use most often.',
      accountDescSub: 'Examples: daily spending account, emergency fund, card payment account. Leave it blank to skip saving.',
      addAccount: 'Add account',
      accountPlaceholder: 'e.g. Main account',
      delete: 'Delete',
      budgetTitle: 'Monthly budgets',
      budgetDesc: 'Add category budgets and see overages right away in analysis.',
      budgetDescSub: 'Examples: Food 40,000 JPY, Transport 12,000 JPY. Leave it empty if you are not ready yet.',
      addBudget: 'Add budget',
      budgetPlaceholder: 'e.g. Food budget',
      recurringTitle: 'Recurring entries',
      recurringDesc: 'Pre-register recurring items like rent, salary, and subscriptions.',
      recurringDescSub: 'Examples: rent on the 25th each month, subscription on the 10th. You can add them later too.',
      addRecurring: 'Add recurring entry',
      recurringNamePlaceholder: 'e.g. Rent',
      recurringDescriptionPlaceholder: 'Description',
      withdrawalAccount: 'Withdrawal account',
      depositAccount: 'Deposit account',
      accountSelect: 'Select account',
      monthly: 'Monthly',
      weekly: 'Weekly',
      yearly: 'Yearly',
      executionDay: 'Run day',
      previous: 'Previous',
      next: 'Next',
      saving: 'Saving...',
      complete: 'Finish onboarding',
    },
    managers: {
      budgetTitle: 'Budget management',
      budgetDesc: 'Register category budgets and confirm overages instantly in analysis.',
      budgetPlaceholder: 'e.g. Food budget',
      saveBudget: 'Save budget',
      currentBudgets: 'Current budgets',
      noBudgets: 'No budgets have been added yet.',
      recurringTitle: 'Recurring management',
      recurringDesc: 'Manage repeating items like rent, subscriptions, and salary in one place.',
      recurringNamePlaceholder: 'e.g. Rent',
      recurringDescPlaceholder: 'e.g. Monthly rent',
      selectAccount: 'Select account',
      saveRecurring: 'Save recurring entry',
      recurringMigrationHint: 'You can keep using normal transactions for now. This screen will work as soon as the recurring table is applied in production.',
      currentRecurring: 'Current recurring entries',
      noRecurring: 'No recurring entries have been added yet.',
      periodMonthLabel: (year: number, month: number) => `${year}.${String(month).padStart(2, '0')}`,
      dayOfMonthLabel: 'Monthly run day',
      dayOfMonthHint: 'Choose which day of each month this entry should be created.',
      alertThresholdLabel: 'Alert threshold (%)',
      alertThresholdHint: 'Choose when the budget should start warning you.',
      activeLabel: 'Active',
      inactiveLabel: 'Inactive',
      deleteBudgetConfirm: 'Delete this budget?',
      deleteRecurringConfirm: 'Delete this recurring entry?',
      saveChanges: 'Save changes',
      categoryTitle: 'Category management',
      categoryDesc: 'Create your own income and expense categories for transaction entry.',
      categoryPlaceholder: 'e.g. Pets, family events',
      addCategory: 'Add category',
      currentCategories: 'Current categories',
      defaultTag: 'Default',
      customTag: 'Custom',
      createCategoryFailed: 'Unable to add the category.',
      deleteCategoryFailed: 'Unable to delete the category.',
      updateCategoryFailed: 'Unable to update the category.',
    },
    investmentPortfolio: {
      loadError: 'Unable to load investment data.',
      empty: 'No investments have been added yet.',
      deleteAction: 'Delete',
      deleteConfirm: 'Delete this investment? This only removes the investment record and does not affect the linked account balance.',
      deleteFailed: 'Unable to delete the investment.',
      totalCount: (count: number) => `${count} investment positions`,
      portfolioValue: 'Portfolio value',
      marketValueHint: 'Valuation based on auto-refreshed market prices (JPY)',
      totalGainLoss: 'Total gain/loss',
      cumulativeReturn: 'Cumulative investment return',
      nisaLimit: 'NISA annual limit (growth allocation)',
      annualLimit: '1.2M JPY / year',
      usedAmount: 'Used',
      remainingLimit: 'Remaining',
      byType: 'By investment type',
      regular: 'Regular',
      itemCount: (count: number) => `${count} positions`,
      byMarket: 'By market',
      jpMarket: 'Japan market',
      usMarket: 'US market',
      diversification: 'Allocation',
      holdingsCta: 'Add your first investment to start building the portfolio.',
    },
    bulkImport: {
      failed: 'Bulk transaction import failed',
      success: 'Transactions were added successfully.',
      dateRequired: 'Please enter a date.',
      descriptionRequired: 'Please enter a description.',
      amountRequired: 'Please enter a valid amount.',
      accountRequired: 'Please choose an account.',
      fillAll: 'Please fill in all fields.',
      accountNotFound: (name: string) => `Account not found: ${name}`,
      csvParseError: (message: string) => `CSV parse error: ${message}`,
      noTransactions: 'There are no transactions to import.',
      fixErrors: 'Some transactions still contain errors. Please fix them first.',
      title: 'Bulk transaction import',
      subtitle: 'Add many transactions in one pass.',
      methodTitle: 'Choose import method',
      manual: 'Manual entry',
      manualDesc: 'Enter one row at a time',
      csv: 'CSV upload',
      csvDesc: 'Import from a file',
      addEntryTitle: 'Add transaction',
      date: 'Date',
      account: 'Account',
      selectAccount: 'Select account',
      description: 'Description',
      descriptionPlaceholder: 'e.g. Lunch',
      amount: 'Amount',
      type: 'Type',
      addRow: 'Add row',
      csvUploadTitle: 'Upload CSV file',
      csvDrop: 'Drag a CSV file here or click to browse',
      csvFormat: 'Format: date, description, type, amount, account name, currency',
      csvExample: 'CSV example',
      scheduled: (count: number) => `Pending transactions (${count})`,
      dateLabel: (date: string) => `Date: ${date}`,
      accountLabel: (account: string) => `Account: ${account}`,
      typeLabel: (type: string) => `Type: ${type}`,
      importing: 'Importing...',
      submit: (count: number) => `Import transactions (${count})`,
      errorTitle: 'Bulk import error',
    },
    transactionForm: {
      duplicateError: 'A transaction with the same date, amount, type, and description already exists.',
      applyBalance: 'Apply to current account balance',
      applyBalanceDesc: 'Today’s transactions update the current balance automatically. Past transactions stay as records by default, and you can opt in to adjust the balance when needed.',
      todayAuto: 'This is a transaction for today, so the balance will update automatically.',
      pastOptional: 'This is a past transaction. Enable this if you also want to adjust the current balance.',
      duplicateHint: 'A very similar transaction already exists.',
      descriptionPlaceholder: 'e.g. Lunch, Salary',
    },
    transactionList: {
      selectAll: (count: number) => `Select all (${count})`,
      notAvailable: '-',
    },
    goals: {
      workspaceLabel: 'Goal workspace',
      classicSubtitle: 'Set goals and keep progress visible in one place.',
    },
  },
  ja: {
    language: { changeTitle: '言語を変更' },
    register: {
      strengthLabels: ['とても弱い', '弱い', '普通', '強い', 'とても強い'],
      passwordTyping: '入力中',
      passwordMismatch: 'パスワードが一致しません。',
      passwordMin: 'パスワードは8文字以上で入力してください。',
      registerSuccess: '登録が完了しました。確認メールをご確認ください。',
      createAccount: 'アカウント作成',
      passwordStrength: 'パスワード強度',
      passwordGuide: '8文字以上で、大文字・数字・記号を含めるのがおすすめです。',
      passwordMatch: 'パスワードが一致しています',
      passwordMismatchInline: 'パスワードが一致しません',
      registerFailTitle: '登録に失敗しました',
      successTitle: '完了',
      signingUp: '登録中...',
      signUp: '登録する',
      or: 'または',
      alreadyHaveAccount: 'すでにアカウントをお持ちですか？',
      login: 'ログイン',
      footer: '個人資産ワークスペース',
      emailLabel: 'メールアドレス',
      emailPlaceholder: 'name@example.com',
      passwordLabel: 'パスワード',
      passwordPlaceholder: 'パスワードを入力',
      confirmPasswordLabel: 'パスワード確認',
      confirmPasswordPlaceholder: 'もう一度入力してください',
    },
    login: {
      liveWorkspace: 'Live workspace',
      screenTitle: '今日のファイナンス画面',
      netWorth: '純資産',
      weekGain: '今週 +2.4%',
      recentExpense: '最近の支出',
      goalProgress: '目標進捗',
      recentTransactions: '最近の取引',
      today: 'Today',
      food: '食費',
      salary: '給与',
      investment: '投資',
      or: 'または',
      sampleLunch: '昼食',
      sampleSalary: '給与',
      sampleEtf: 'ETF買付',
      emailPlaceholder: 'name@example.com',
      passwordPlaceholder: 'パスワードを入力',
    },
    authRecovery: {
      forgotTitle: 'パスワードを再設定',
      forgotDesc: '登録したメールアドレスを入力すると、再設定リンクを送信します。',
      emailLabel: 'メールアドレス',
      emailPlaceholder: 'name@example.com',
      sendReset: '再設定リンクを送信',
      genericError: 'エラーが発生しました。',
      unexpectedError: '予期しないエラーが発生しました。もう一度お試しください。',
      resetTitle: '新しいパスワードを設定',
      resetDesc: 'ログイン済みです。下記に新しいパスワードを入力してください。',
      authError: '認証を確認できませんでした。新しい再設定リンクからやり直してください。',
      passwordMismatch: 'パスワードが一致しません。',
      passwordMin: 'パスワードは6文字以上で入力してください。',
      passwordUpdated: 'パスワードを更新しました。ログアウト後、ログイン画面へ移動します。',
      newPasswordLabel: '新しいパスワード',
      newPasswordPlaceholder: '新しいパスワードを入力（6文字以上）',
      confirmPasswordLabel: '新しいパスワード確認',
      confirmPasswordPlaceholder: 'もう一度入力してください',
      submitReset: 'パスワードを変更',
    },
    analysis: {
      label: '分析',
      error: '分析データを読み込めませんでした。',
      emptyTitle: 'まだ表示できるデータがありません。',
      emptyDesc: '取引や予算を入力すると、月別分析とカテゴリ分析がここに表示されます。',
      thisMonth: '今月',
      netSavings: '純貯蓄',
      monthOverMonth: '前月比',
      expenseChange: '支出の変化',
      exchangeFlow: '両替の流れ',
      exchangeFlowDesc: '月ごとの両替件数と規模を通常支出とは分けて確認します。',
      exchangeCount: (count: number) => `両替 ${count}件`,
      openSettings: '設定を開く',
      budgetSetup: '予算設定',
      recurringSetup: '定期取引設定',
      overBudgetCount: (count: number) => `超過予算 ${count}件`,
      budgetHint: '月次予算を登録すると超過状況をここで確認できます。',
      recurringHintActive: '家賃、サブスク、給与などの定期取引を管理します。',
      recurringHintEmpty: '定期取引を登録して入力の手間を減らしましょう。',
      monthlyCashflow: '月別キャッシュフロー',
      monthlyCashflowDesc: '直近12か月の収入・支出・純貯蓄の推移です。',
      monthlyCategory: '月別カテゴリ分析',
      monthlyCategoryDesc: '今月を基準に、見たい月の支出カテゴリを確認できます。',
      noMonthlyCategory: '選択した月のカテゴリ支出はまだありません。',
      viewAllCategories: 'すべてのカテゴリを見る',
      yearlyTrend: '年別推移',
      yearlyTrendDesc: '年単位で収入と支出の流れを比較します。',
      budgetStatus: '予算状況',
      budgetStatusDesc: '現在の月次予算と実際の支出を比較します。',
      budgetEmpty: '登録された月次予算がまだありません。予算を追加すると使用率と超過状況を確認できます。',
      daysRemaining: (days: number) => `残り ${days} 日`,
      categoryPageLabel: 'カテゴリ分析',
      categoryPageError: 'カテゴリ分析データを読み込めませんでした。',
      categoryPageTitle: 'カテゴリ別支出一覧',
      categoryPageDesc: (month: string) => `${month}の支出カテゴリをすべて確認できます。`,
      backToAnalysis: '分析に戻る',
      categoryAmount: 'カテゴリ別金額',
      totalExpense: (amount: string, currency: string) => `総支出 ${amount} ${currency}`,
      noCategoryExpense: '選択した月の支出カテゴリはまだありません。',
    },
    overview: {
      expenseUp: '支出が増えています',
      expenseStable: '支出は安定しています',
      quickAdd: 'クイック追加',
      addTransaction: '取引追加',
      addTransactionDesc: '支出・収入・振替をすぐ記録',
      assetSetup: '資産設定',
      addAccount: '口座追加',
      addAccountDesc: '新しい口座やカードを追加',
      portfolio: 'ポートフォリオ',
      addInvestment: '投資追加',
      addInvestmentDesc: '保有銘柄をすばやく登録',
      assetOverview: '資産概要',
      recent30Days: '直近30日ベース',
      estimatedBeforeRates: '為替同期前の推定値',
      heroDesc: '今日の資産状況と最近の支出の流れを一画面で見て、どこから整えるべきかすぐ判断できるようにしました。',
      recent30DayExpense: '直近30日の支出',
      investment: '投資',
      averageGoalProgress: '目標平均進捗',
      jumpNow: '開く',
      focusPoint: '今見ておきたいポイント',
      focusDescUp: '最近の支出が前回の流れより増えています。増えたカテゴリから先に確認するのがおすすめです。',
      focusDescStable: '支出の流れは比較的安定しています。余った現金を目標や投資に回す余地があります。',
      basedOnNetWorth: '純資産ベース',
      linkedAccounts: '連携口座数',
      investmentAssets: '投資資産合計',
      expenseChange: '最近の支出変化',
      dayOverDayExpense: '前日比',
      plannedExpenses: '支出予定',
      plannedExpensesMeta: (recurringCount: number, cardCount: number) => `定期取引 ${recurringCount} 件 · カード支払 ${cardCount} 件`,
      analysisGraphMode: 'グラフ表示',
      analysisGraphBar: '棒グラフ',
      analysisGraphDot: '点線グラフ',
      amountLabel: '金額',
      amountHint: '選択した月に管理したい予算金額です。',
      currencyLabel: '通貨',
      yearLabel: '年',
      monthLabel: '月',
      krwMirror: 'ウォン換算参考額',
      activeGoals: '有効な目標数',
      cashBalance: '現金残高',
      cashByCurrency: '通貨別現金残高',
      aiShortcutLabel: 'Beta shortcut',
      aiShortcutTitle: 'AIで下書き登録',
      aiShortcutDesc: '複数の取引を貼り付けると、カテゴリまでまとめて下書きできます。',
      openBeta: 'Betaを開く',
      focusNow: '今の注目点',
      currentGoalLabel: '現在の目標',
      primaryGoalTitle: '最優先目標',
      currencyBucket: '通貨別区分',
      otherExpenseCategory: 'その他',
      expenseSplit: '支出の流れ',
      currencyBalances: '通貨別資産',
      currencyBalancesDesc: '口座残高と投資資産を通貨ごとにまとめて確認できます。',
      baseCurrencyLabel: '基準通貨',
      mirrorCurrencyLabel: '参考通貨',
      mirrorCardLabel: (currency: string) => `${currency} ミラー`,
      totalAssetsInCurrency: (currency: string) => `総資産 (${currency})`,
      recentExpenseInCurrency: (currency: string) => `直近30日の支出 (${currency})`,
      investmentInCurrency: (currency: string) => `投資 (${currency})`,
      expenseChangeInCurrency: (currency: string) => `支出変化 (${currency})`,
    },
    holdingsForm: {
      genericError: 'エラーが発生しました。',
      fillRequired: '必須項目をすべて入力してください。',
      pickHoldingAction: '買い増しまたは売却する投資を選択してください。',
      pickSuggestion: '検索結果から銘柄を選択してください。',
      numberOnly: '数量と価格は数字で入力してください。',
      positiveOnly: '数量と価格は0より大きくしてください。',
      buyTitle: '買い増し',
      sellTitle: '売却',
      buyDesc: '既存の投資に数量を追加し、平均取得単価を自動で再計算します。',
      sellDesc: '保有数量を減らすか、全量売却します。',
      createDesc: 'ポートフォリオに株式や投資商品を追加します。',
      actionLabel: '投資アクション',
      createOption: '新規投資を追加',
      buyOption: '買い増し',
      sellOption: '売却',
      targetHolding: '対象投資',
      selectHolding: '投資を選択',
      unnamed: '名称未設定',
      currentHolding: (shares: string, cost: string, currency: string) => `現在保有: ${shares}株 / 平均 ${cost} ${currency}`,
      symbolPlaceholder: '銘柄名またはシンボルで検索',
      searchingSymbol: '銘柄を検索中...',
      noSymbolResults: '一致する銘柄が見つかりませんでした。',
      searchHint: '検索結果から選択するとシンボルの不一致を減らせます。',
      existingHoldingHint: '買い増しと売却は既存の投資を基準に処理します。',
      sellPrice: '売却単価',
      buyPrice: '買付単価',
      estimatedSellAmount: '想定売却金額',
      estimatedBuyAmount: '追加買付金額',
      totalCost: '合計購入金額',
      symbolLinkWarning: '検索結果から選ぶと、正しいシンボルと価格更新が結び付きます。',
      account: '口座',
      selectAccount: '口座を選択',
    },
    setup: {
      defaultBudgetName: '食費予算',
      step1: '口座',
      step2: '予算',
      step3: '定期取引',
      title: 'オンボーディング設定',
      desc: '手入力中心の家計管理に合わせて、口座・予算・定期取引をまとめて準備します。',
      descSub: '今すべて入力する必要はありません。必要なものだけ入れて、残りは後から追加できます。',
      languageTitle: '言語設定',
      languageDesc: '先に言語を選ぶと、基本カテゴリと初期サンプルもその言語に合わせて準備されます。',
      currencyTitle: 'よく使う通貨',
      currencyDesc: 'よく使う通貨を先に選ぶと、ダッシュボードと為替一覧がより自然に始まります。',
      baseCurrencyLabel: '基準通貨',
      mirrorCurrencyLabel: '参考通貨',
      trackedCurrenciesLabel: '追跡通貨',
      trackedCurrenciesDesc: '最低2つを選ぶと、為替一覧と自動更新を必要な通貨だけに絞れます。',
      securityTitle: 'セキュリティ優先',
      securityDesc: 'すべてのデータはログイン中のユーザー所有でのみ保存され、オンボーディング完了前はメイン画面に進めないようにしています。',
      skip: '今はスキップ',
      onboardingFailed: '初期設定に失敗しました。',
      skipFailed: 'オンボーディングのスキップに失敗しました。',
      accountTitle: '口座登録',
      accountDesc: 'よく使う口座と初期残高を先に設定しましょう。',
      accountDescSub: '例: 生活費口座、緊急資金口座、カード引き落とし口座。空欄なら保存せずに進めます。',
      addAccount: '口座追加',
      accountPlaceholder: '例: メイン口座',
      delete: '削除',
      budgetTitle: '月別予算',
      budgetDesc: 'カテゴリごとの予算を設定すると、分析タブですぐ超過状況を確認できます。',
      budgetDescSub: '例: 食費 40,000円、交通費 12,000円。まだ決めていなければ空欄でも構いません。',
      addBudget: '予算追加',
      budgetPlaceholder: '例: 食費予算',
      recurringTitle: '定期取引',
      recurringDesc: '家賃、給与、サブスクのような繰り返し取引をあらかじめ登録しておきましょう。',
      recurringDescSub: '例: 毎月25日の家賃、毎月10日のサブスク。あとから追加しても大丈夫です。',
      addRecurring: '定期取引追加',
      recurringNamePlaceholder: '例: 家賃',
      recurringDescriptionPlaceholder: '説明',
      withdrawalAccount: '出金口座',
      depositAccount: '入金口座',
      accountSelect: '口座を選択',
      monthly: '毎月',
      weekly: '毎週',
      yearly: '毎年',
      executionDay: '実行日',
      previous: '前へ',
      next: '次へ',
      saving: '保存中...',
      complete: 'オンボーディング完了',
    },
    managers: {
      budgetTitle: '予算管理',
      budgetDesc: '月別カテゴリ予算を登録すると、分析タブですぐ超過状況を確認できます。',
      budgetPlaceholder: '例: 食費予算',
      saveBudget: '予算を保存',
      currentBudgets: '現在の予算',
      noBudgets: '登録された予算がありません。',
      recurringTitle: '定期取引管理',
      recurringDesc: '家賃、サブスク、給与のような繰り返し取引をまとめて管理します。',
      recurringNamePlaceholder: '例: 家賃',
      recurringDescPlaceholder: '例: 毎月の家賃',
      selectAccount: '口座を選択',
      saveRecurring: '定期取引を保存',
      recurringMigrationHint: '今は通常の取引登録を使い続けられます。運用DBに定期取引テーブルが適用されると、この画面からそのまま使えます。',
      currentRecurring: '現在の定期取引',
      noRecurring: '登録された定期取引がありません。',
      periodMonthLabel: (year: number, month: number) => `${year}.${String(month).padStart(2, '0')}`,
      dayOfMonthLabel: '毎月の実行日',
      dayOfMonthHint: '毎月何日に自動登録するかを決めます。',
      alertThresholdLabel: 'アラート基準 (%)',
      alertThresholdHint: '予算の何％から警告するかを設定します。',
      activeLabel: '有効',
      inactiveLabel: '停止',
      deleteBudgetConfirm: 'この予算を削除しますか？',
      deleteRecurringConfirm: 'この定期取引を削除しますか？',
      saveChanges: '変更を保存',
      categoryTitle: 'カテゴリ管理',
      categoryDesc: '取引入力で使う収入・支出カテゴリを自分で追加できます。',
      categoryPlaceholder: '例: ペット、冠婚葬祭',
      addCategory: 'カテゴリ追加',
      currentCategories: '現在のカテゴリ',
      defaultTag: '基本',
      customTag: 'ユーザー',
      createCategoryFailed: 'カテゴリを追加できませんでした。',
      deleteCategoryFailed: 'カテゴリを削除できませんでした。',
      updateCategoryFailed: 'カテゴリを更新できませんでした。',
    },
    investmentPortfolio: {
      loadError: '投資データを読み込めませんでした。',
      empty: '登録された投資がありません。',
      deleteAction: '削除',
      deleteConfirm: 'この投資を削除しますか？口座残高には影響せず、投資記録のみ削除されます。',
      deleteFailed: '投資を削除できませんでした。',
      totalCount: (count: number) => `全${count}件の投資銘柄`,
      portfolioValue: 'ポートフォリオ価値',
      marketValueHint: '自動更新された現在値ベースの評価額 (JPY)',
      totalGainLoss: '総損益',
      cumulativeReturn: '累計投資収益',
      nisaLimit: 'NISA投資枠 (成長投資枠)',
      annualLimit: '年間120万円',
      usedAmount: '使用額',
      remainingLimit: '残り枠',
      byType: '投資タイプ別',
      regular: '一般',
      itemCount: (count: number) => `${count}銘柄`,
      byMarket: '市場別構成',
      jpMarket: '日本市場',
      usMarket: '米国市場',
      diversification: '投資比率',
      holdingsCta: '最初の投資を追加してポートフォリオを始めましょう。',
    },
    bulkImport: {
      failed: '取引の一括入力に失敗しました',
      success: '取引が正常に登録されました。',
      dateRequired: '日付を入力してください。',
      descriptionRequired: '説明を入力してください。',
      amountRequired: '有効な金額を入力してください。',
      accountRequired: '口座を選択してください。',
      fillAll: 'すべての項目を入力してください。',
      accountNotFound: (name: string) => `口座が見つかりません: ${name}`,
      csvParseError: (message: string) => `CSV解析エラー: ${message}`,
      noTransactions: '入力する取引がありません。',
      fixErrors: 'エラーのある取引があります。修正してください。',
      title: '取引一括入力',
      subtitle: '複数の取引をまとめて入力できます。',
      methodTitle: '入力方法を選択',
      manual: '手動入力',
      manualDesc: '1件ずつ入力',
      csv: 'CSVアップロード',
      csvDesc: 'ファイルから一括入力',
      addEntryTitle: '取引を追加',
      date: '日付',
      account: '口座',
      selectAccount: '口座を選択',
      description: '説明',
      descriptionPlaceholder: '例: 昼食',
      amount: '金額',
      type: '種類',
      addRow: '取引追加',
      csvUploadTitle: 'CSVファイルをアップロード',
      csvDrop: 'CSVファイルをここにドラッグするかクリックしてください',
      csvFormat: '形式: 日付, 説明, 種類, 金額, 口座名, 通貨',
      csvExample: 'CSV形式の例',
      scheduled: (count: number) => `入力予定の取引 (${count}件)`,
      dateLabel: (date: string) => `日付: ${date}`,
      accountLabel: (account: string) => `口座: ${account}`,
      typeLabel: (type: string) => `種類: ${type}`,
      importing: '入力中...',
      submit: (count: number) => `取引を入力 (${count}件)`,
      errorTitle: '取引入力エラー',
    },
    transactionForm: {
      duplicateError: '同じ日付・金額・種類・説明の取引がすでに登録されています。',
      applyBalance: '現在の口座残高にも反映',
      applyBalanceDesc: '今日の取引は自動で残高に反映されます。過去の取引は記録のみが基本で、必要な場合だけ残高補正を有効にできます。',
      todayAuto: '今日の取引なので残高に自動反映されます。',
      pastOptional: '過去の取引です。必要ならチェックして現在残高も補正できます。',
      duplicateHint: '重複の可能性が高い取引がすでにあります。',
      descriptionPlaceholder: '例: 昼食、給与',
    },
    transactionList: {
      selectAll: (count: number) => `すべて選択 (${count})`,
      notAvailable: '-',
    },
    goals: {
      workspaceLabel: '目標ワークスペース',
      classicSubtitle: '目標を設定し、進捗をひと目で確認できます。',
    },
  },
  zh: {
    language: { changeTitle: '切换语言' },
    register: {
      strengthLabels: ['非常弱', '弱', '一般', '强', '非常强'],
      passwordTyping: '输入中',
      passwordMismatch: '密码不一致。',
      passwordMin: '密码至少需要 8 个字符。',
      registerSuccess: '注册完成，请检查你的邮箱。',
      createAccount: '创建账户',
      passwordStrength: '密码强度',
      passwordGuide: '建议至少 8 位，并包含大写字母、数字和符号。',
      passwordMatch: '密码一致',
      passwordMismatchInline: '密码不一致',
      registerFailTitle: '注册失败',
      successTitle: '成功',
      signingUp: '注册中...',
      signUp: '注册',
      or: '或',
      alreadyHaveAccount: '已经有账户了吗？',
      login: '登录',
      footer: '个人资产工作区',
      emailLabel: '邮箱',
      emailPlaceholder: 'name@example.com',
      passwordLabel: '密码',
      passwordPlaceholder: '请输入密码',
      confirmPasswordLabel: '确认密码',
      confirmPasswordPlaceholder: '请再次输入密码',
    },
    login: {
      liveWorkspace: 'Live workspace',
      screenTitle: '今日财务画面',
      netWorth: '净资产',
      weekGain: '本周 +2.4%',
      recentExpense: '最近支出',
      goalProgress: '目标进度',
      recentTransactions: '最近交易',
      today: 'Today',
      food: '餐饮',
      salary: '工资',
      investment: '投资',
      or: '或',
      sampleLunch: '午餐',
      sampleSalary: '工资',
      sampleEtf: 'ETF 买入',
      emailPlaceholder: 'name@example.com',
      passwordPlaceholder: '请输入密码',
    },
    authRecovery: {
      forgotTitle: '重置密码',
      forgotDesc: '输入你的注册邮箱，我们会发送密码重置链接。',
      emailLabel: '邮箱地址',
      emailPlaceholder: 'name@example.com',
      sendReset: '发送重置链接',
      genericError: '发生错误。',
      unexpectedError: '发生意外错误，请重试。',
      resetTitle: '设置新密码',
      resetDesc: '你当前已登录，请在下方输入新密码。',
      authError: '无法验证身份，请使用新的重置链接重新尝试。',
      passwordMismatch: '两次输入的密码不一致。',
      passwordMin: '密码长度至少为 6 个字符。',
      passwordUpdated: '密码已更新。你将被登出并跳转到登录页面。',
      newPasswordLabel: '新密码',
      newPasswordPlaceholder: '输入新密码（至少 6 位）',
      confirmPasswordLabel: '确认新密码',
      confirmPasswordPlaceholder: '再次输入新密码',
      submitReset: '更新密码',
    },
    analysis: {
      label: '分析',
      error: '无法加载分析数据。',
      emptyTitle: '当前还没有可显示的数据。',
      emptyDesc: '录入交易或预算后，这里会显示月度分析和分类分析。',
      thisMonth: '本月',
      netSavings: '净储蓄',
      monthOverMonth: '较上月',
      expenseChange: '支出变化',
      exchangeFlow: '换汇流向',
      exchangeFlowDesc: '将每月换汇次数和规模与普通支出分开查看。',
      exchangeCount: (count: number) => `换汇 ${count} 笔`,
      openSettings: '打开设置',
      budgetSetup: '预算设置',
      recurringSetup: '周期交易设置',
      overBudgetCount: (count: number) => `超预算 ${count} 项`,
      budgetHint: '添加月预算后即可在这里确认是否超支。',
      recurringHintActive: '管理房租、订阅、工资等周期交易。',
      recurringHintEmpty: '添加周期交易，减少手动录入负担。',
      monthlyCashflow: '月度现金流',
      monthlyCashflowDesc: '最近 12 个月的收入、支出和净储蓄变化。',
      monthlyCategory: '月度分类分析',
      monthlyCategoryDesc: '默认显示本月，也可以切换查看过去月份的支出分类。',
      noMonthlyCategory: '所选月份还没有分类支出记录。',
      viewAllCategories: '查看全部分类',
      yearlyTrend: '年度趋势',
      yearlyTrendDesc: '按年份比较收入与支出的变化。',
      budgetStatus: '预算状态',
      budgetStatusDesc: '比较当前月预算和实际支出。',
      budgetEmpty: '还没有登记月预算。添加后即可在这里查看使用率和超支情况。',
      daysRemaining: (days: number) => `还剩 ${days} 天`,
      categoryPageLabel: '分类分析',
      categoryPageError: '无法加载分类分析数据。',
      categoryPageTitle: '全部分类支出',
      categoryPageDesc: (month: string) => `查看 ${month} 的全部支出分类。`,
      backToAnalysis: '返回分析',
      categoryAmount: '分类金额',
      totalExpense: (amount: string, currency: string) => `总支出 ${amount} ${currency}`,
      noCategoryExpense: '所选月份还没有支出分类。',
    },
    overview: {
      expenseUp: '支出正在增加',
      expenseStable: '支出较稳定',
      quickAdd: '快速添加',
      addTransaction: '添加交易',
      addTransactionDesc: '立即记录支出、收入或转账',
      assetSetup: '资产设置',
      addAccount: '添加账户',
      addAccountDesc: '添加新的账户或卡片',
      portfolio: '投资组合',
      addInvestment: '添加投资',
      addInvestmentDesc: '快速登记持仓',
      assetOverview: '资产概览',
      recent30Days: '基于最近 30 天',
      estimatedBeforeRates: '汇率同步前估算值',
      heroDesc: '在一个画面里查看今天的资产状态和最近支出趋势，更快判断该先处理什么。',
      recent30DayExpense: '最近 30 天支出',
      investment: '投资',
      averageGoalProgress: '目标平均进度',
      jumpNow: '进入',
      focusPoint: '现在值得关注',
      focusDescUp: '最近支出高于前一段时间，建议先看看哪些分类增长了。',
      focusDescStable: '支出走势相对稳定，可以考虑把剩余现金转向目标或投资。',
      basedOnNetWorth: '基于净资产',
      linkedAccounts: '已连接账户',
      investmentAssets: '投资资产合计',
      expenseChange: '最近支出变化',
      dayOverDayExpense: '较前一日',
      plannedExpenses: '预计支出',
      plannedExpensesMeta: (recurringCount: number, cardCount: number) => `周期交易 ${recurringCount} 条 · 信用卡还款 ${cardCount} 条`,
      analysisGraphMode: '图表方式',
      analysisGraphBar: '柱状图',
      analysisGraphDot: '点线图',
      amountLabel: '金额',
      amountHint: '这是你希望在所选月份管理的预算金额。',
      currencyLabel: '货币',
      yearLabel: '年份',
      monthLabel: '月份',
      krwMirror: '韩元参考视图',
      activeGoals: '进行中的目标',
      cashBalance: '现金余额',
      cashByCurrency: '按货币现金余额',
      aiShortcutLabel: 'Beta shortcut',
      aiShortcutTitle: '使用 AI 草拟录入',
      aiShortcutDesc: '粘贴多条交易后，可一次性整理出分类和结构草稿。',
      openBeta: '打开 Beta',
      focusNow: '当前重点',
      currentGoalLabel: '当前目标',
      primaryGoalTitle: '优先目标',
      currencyBucket: '货币分组',
      otherExpenseCategory: '其他',
      expenseSplit: '支出分布',
      currencyBalances: '按货币查看资产',
      currencyBalancesDesc: '按货币汇总查看账户余额和投资资产。',
      baseCurrencyLabel: '基准货币',
      mirrorCurrencyLabel: '参考货币',
      mirrorCardLabel: (currency: string) => `${currency} 参考`,
      totalAssetsInCurrency: (currency: string) => `总资产 (${currency})`,
      recentExpenseInCurrency: (currency: string) => `近30天支出 (${currency})`,
      investmentInCurrency: (currency: string) => `投资 (${currency})`,
      expenseChangeInCurrency: (currency: string) => `支出变化 (${currency})`,
    },
    holdingsForm: {
      genericError: '发生错误。',
      fillRequired: '请填写所有必填项。',
      pickHoldingAction: '请选择要加仓或卖出的投资。',
      pickSuggestion: '请从搜索结果中选择一个标的。',
      numberOnly: '数量和价格必须为数字。',
      positiveOnly: '数量和价格必须大于 0。',
      buyTitle: '追加买入',
      sellTitle: '卖出',
      buyDesc: '在现有持仓上继续买入，并自动重新计算平均成本。',
      sellDesc: '减少现有持仓数量或全部卖出。',
      createDesc: '向投资组合中添加股票或投资产品。',
      actionLabel: '投资操作',
      createOption: '新增投资',
      buyOption: '追加买入',
      sellOption: '卖出',
      targetHolding: '目标投资',
      selectHolding: '选择投资',
      unnamed: '未命名',
      currentHolding: (shares: string, cost: string, currency: string) => `当前持有: ${shares} 股 / 均价 ${cost} ${currency}`,
      symbolPlaceholder: '按公司名或代码搜索',
      searchingSymbol: '正在搜索标的...',
      noSymbolResults: '未找到匹配的标的。',
      searchHint: '从搜索结果中选择可以减少代码不匹配问题。',
      existingHoldingHint: '追加买入和卖出都基于已有持仓处理。',
      sellPrice: '卖出价',
      buyPrice: '买入价',
      estimatedSellAmount: '预计卖出金额',
      estimatedBuyAmount: '预计买入金额',
      totalCost: '总买入金额',
      symbolLinkWarning: '请从搜索结果中选择，这样才能正确关联代码和价格更新。',
      account: '账户',
      selectAccount: '选择账户',
    },
    setup: {
      defaultBudgetName: '餐饮预算',
      step1: '账户',
      step2: '预算',
      step3: '周期交易',
      title: '引导设置',
      desc: '为手动输入型的财务记录流程，一次性准备账户、预算和周期交易。',
      descSub: '现在不必全部填写。先录入需要的内容，其余稍后再补充也可以。',
      languageTitle: '语言设置',
      languageDesc: '先选择语言后，默认分类和初始示例也会按该语言准备。',
      currencyTitle: '常用货币',
      currencyDesc: '先选出真正会使用的货币，让仪表盘和汇率列表从一开始就更贴合你的习惯。',
      baseCurrencyLabel: '基准货币',
      mirrorCurrencyLabel: '参考货币',
      trackedCurrenciesLabel: '跟踪货币',
      trackedCurrenciesDesc: '至少选择两种，只保留你真正需要关注的汇率和自动更新。',
      securityTitle: '安全优先',
      securityDesc: '所有数据都只会保存到当前登录用户名下，且在完成引导前不会进入主界面。',
      skip: '先跳过',
      onboardingFailed: '完成初始化设置失败。',
      skipFailed: '跳过引导失败。',
      accountTitle: '添加账户',
      accountDesc: '先设置你最常用的账户和初始余额。',
      accountDescSub: '例如：生活费账户、应急金账户、信用卡还款账户。留空则不保存直接跳过。',
      addAccount: '添加账户',
      accountPlaceholder: '例如：主账户',
      delete: '删除',
      budgetTitle: '月度预算',
      budgetDesc: '设置分类预算后，就能在分析页立即看到是否超支。',
      budgetDescSub: '例如：餐饮 40,000 日元，交通 12,000 日元。如果暂时还没计划，可以先留空。',
      addBudget: '添加预算',
      budgetPlaceholder: '例如：餐饮预算',
      recurringTitle: '周期交易',
      recurringDesc: '预先登记房租、工资、订阅等重复发生的交易。',
      recurringDescSub: '例如：每月 25 日房租、每月 10 日订阅。之后再添加也没问题。',
      addRecurring: '添加周期交易',
      recurringNamePlaceholder: '例如：房租',
      recurringDescriptionPlaceholder: '说明',
      withdrawalAccount: '转出账户',
      depositAccount: '转入账户',
      accountSelect: '选择账户',
      monthly: '每月',
      weekly: '每周',
      yearly: '每年',
      executionDay: '执行日',
      previous: '上一步',
      next: '下一步',
      saving: '保存中...',
      complete: '完成引导',
    },
    managers: {
      budgetTitle: '预算管理',
      budgetDesc: '登记月度分类预算后，可在分析页立即查看是否超支。',
      budgetPlaceholder: '例如：餐饮预算',
      saveBudget: '保存预算',
      currentBudgets: '当前预算',
      noBudgets: '还没有登记预算。',
      recurringTitle: '周期交易管理',
      recurringDesc: '在一个地方管理房租、订阅、工资等重复交易。',
      recurringNamePlaceholder: '例如：房租',
      recurringDescPlaceholder: '例如：每月房租',
      selectAccount: '选择账户',
      saveRecurring: '保存周期交易',
      recurringMigrationHint: '目前仍可继续使用普通交易录入。待生产数据库应用周期交易表后，这个页面会直接可用。',
      currentRecurring: '当前周期交易',
      noRecurring: '还没有登记周期交易。',
      periodMonthLabel: (year: number, month: number) => `${year}.${String(month).padStart(2, '0')}`,
      dayOfMonthLabel: '每月执行日',
      dayOfMonthHint: '设置每月哪一天自动生成这条交易。',
      alertThresholdLabel: '提醒阈值 (%)',
      alertThresholdHint: '设置预算达到多少百分比时开始提醒。',
      activeLabel: '启用',
      inactiveLabel: '停用',
      deleteBudgetConfirm: '确定删除这个预算吗？',
      deleteRecurringConfirm: '确定删除这条周期交易吗？',
      saveChanges: '保存更改',
      categoryTitle: '分类管理',
      categoryDesc: '可以为交易录入添加自己的收入和支出分类。',
      categoryPlaceholder: '例如：宠物、礼金',
      addCategory: '添加分类',
      currentCategories: '当前分类',
      defaultTag: '默认',
      customTag: '用户',
      createCategoryFailed: '无法添加分类。',
      deleteCategoryFailed: '无法删除分类。',
      updateCategoryFailed: '无法修改分类。',
    },
    investmentPortfolio: {
      loadError: '无法加载投资数据。',
      empty: '还没有登记任何投资。',
      deleteAction: '删除',
      deleteConfirm: '确定要删除这项投资吗？这只会删除投资记录，不会影响关联账户余额。',
      deleteFailed: '无法删除这项投资。',
      totalCount: (count: number) => `共 ${count} 个投资标的`,
      portfolioValue: '投资组合价值',
      marketValueHint: '基于自动更新现价的估值 (JPY)',
      totalGainLoss: '总盈亏',
      cumulativeReturn: '累计投资收益',
      nisaLimit: 'NISA 投资额度（成长投资额度）',
      annualLimit: '每年 120 万日元',
      usedAmount: '已使用',
      remainingLimit: '剩余额度',
      byType: '按投资类型',
      regular: '普通',
      itemCount: (count: number) => `${count} 个标的`,
      byMarket: '按市场分布',
      jpMarket: '日本市场',
      usMarket: '美国市场',
      diversification: '投资占比',
      holdingsCta: '先添加第一笔投资，开始构建你的投资组合。',
    },
    bulkImport: {
      failed: '批量录入交易失败',
      success: '交易已成功录入。',
      dateRequired: '请输入日期。',
      descriptionRequired: '请输入说明。',
      amountRequired: '请输入有效金额。',
      accountRequired: '请选择账户。',
      fillAll: '请填写所有字段。',
      accountNotFound: (name: string) => `找不到账户：${name}`,
      csvParseError: (message: string) => `CSV 解析错误：${message}`,
      noTransactions: '没有可录入的交易。',
      fixErrors: '仍有带错误的交易，请先修正。',
      title: '批量录入交易',
      subtitle: '一次性录入多笔交易。',
      methodTitle: '选择录入方式',
      manual: '手动录入',
      manualDesc: '逐条添加',
      csv: '上传 CSV',
      csvDesc: '从文件批量导入',
      addEntryTitle: '添加交易',
      date: '日期',
      account: '账户',
      selectAccount: '选择账户',
      description: '说明',
      descriptionPlaceholder: '例如：午餐',
      amount: '金额',
      type: '类型',
      addRow: '添加交易',
      csvUploadTitle: '上传 CSV 文件',
      csvDrop: '把 CSV 文件拖到这里，或点击选择文件',
      csvFormat: '格式：日期、说明、类型、金额、账户名、货币',
      csvExample: 'CSV 示例',
      scheduled: (count: number) => `待录入交易（${count} 条）`,
      dateLabel: (date: string) => `日期：${date}`,
      accountLabel: (account: string) => `账户：${account}`,
      typeLabel: (type: string) => `类型：${type}`,
      importing: '录入中...',
      submit: (count: number) => `录入交易（${count} 条）`,
      errorTitle: '交易录入错误',
    },
    transactionForm: {
      duplicateError: '已存在相同日期、金额、类型和说明的交易。',
      applyBalance: '同步到当前账户余额',
      applyBalanceDesc: '今日交易会自动反映到当前余额。过去交易默认只记录明细，需要时也可以手动选择同时校正余额。',
      todayAuto: '这是今天的交易，余额会自动更新。',
      pastOptional: '这是过去的交易，勾选后会同时校正当前余额。',
      duplicateHint: '已经存在一笔高度相似的交易。',
      descriptionPlaceholder: '例如：午餐、工资',
    },
    transactionList: {
      selectAll: (count: number) => `全选 (${count})`,
      notAvailable: '-',
    },
    goals: {
      workspaceLabel: '目标工作区',
      classicSubtitle: '设置目标，并在一个界面里跟踪进度。',
    },
  },
} as const

export function getUiCopy(locale: string) {
  return copy[normalizeLocale(locale)]
}
